name: 💥 Extract Telegram Links

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - 'folder.txt'
  pull_request:
    paths:
      - 'folder.txt'

jobs:
  scrape-and-test:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up Python
        uses: useblacksmith/setup-python@v6
        with:
          python-version: "3.13"

      - name: Cache Python dependencies
        uses: useblacksmith/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Extract Telegram Links
        run: |
          python3 main.py
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_STRING_SESSION: ${{ secrets.TELEGRAM_STRING_SESSION }}          
  
      - name: Upload channels file
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: telegram-channels-${{ github.run_number }}
          path: channels.txt
          retention-days: 30

      - name: Commit channels to repository
        if: ${{ success() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p results
          mv channels.txt results/channels_latest.txt
          git add results/channels_latest.txt
          git commit -m "Updated Telegram Channels for run #${{ github.run_number }}"
          git push origin HEAD:${{ github.ref_name }}